# Generated by Django 4.2.16 on 2024-10-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
