# Generated by Django 4.2.16 on 2024-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0002_alter_contestant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
